## Лабораторная работа 1. Знакомство с библиотеками для анализа данных

Результат лабораторной работы − отчет. Мы предпочитаем принимать отчеты в формате ноутбуков IPython/Jupyter (ipynb-файл). Постарайтесь сделать ваш отчет интересным рассказом, последовательно отвечающим на вопросы из заданий. Помимо ответов на вопросы, в отчете так же должен быть код, однако чем меньше кода, тем лучше всем: нам − меньше проверять, вам —  проще найти ошибку или дополнить эксперимент. При проверке оценивается четкость ответов на вопросы, аккуратность отчета и кода.

Мы уверены, что выполнение лабораторных работ занимает значительное время, поэтому не рекомендуем оставлять их на последний вечер перед сдачей.

### О задании

Лабораторная работа №1 направлена на работу с пакетами для анализа данных. В данной работе разрешено пользоваться только стандартной библиотекой языка Python, а также пакетами NumPy, Pandas и Matplotlib. Целью работы является редактирование данного ipython notebook-a (в части блоков с кодом на python) таким образом, чтобы были реализованы указанные в задании функции.

### Оценивание и штрафы

Каждая из задач имеет определенную «стоимость» (указана в скобках около задачи). Максимально допустимая оценка за работу — 15 баллов.
Сдавать задание после указанного срока сдачи нельзя. «Похожие» решения считаются плагиатом и все задействованные студенты (в том числе те, у кого списали) не могут получить за него больше 0 баллов и понижают карму (подробнее о плагиате см. на странице курса). Если вы нашли решение какого-то из заданий в открытом источнике, необходимо прислать ссылку на этот источник (скорее всего вы будете не единственным, кто это нашел, поэтому для исключения подозрения в плагиате, необходима ссылка на источник).

###  Правила сдачи

Работу необходимо сдавать в систему Anytask (более подробную информацию можно найти на странице курса). Название отправляемого файла должно иметь следующий формат: Surname_Name_Group_NN.ipynb, где NN — номер лабораторной работы. Например, Kozlova_Anna_CS_01.ipynb.

### (8 баллов) Знакомство с Numpy

Во всех заданиях данного раздела запрещено использовать циклы (ключевые слова *for* и *while*). Использование функции *map* также не допускается. Для каждой задачи приведите примеры использования реализованных функций. За отсутствие тестовых примеров могут быть сняты баллы за задание.

Под матрицей в заданиях понимается двумерный numpy.array.

Jupiter hotkeys: http://johnlaudun.org/20131228-ipython-notebook-keyboard-shortcuts/

In [9]:
import numpy as np

**1. (0.5 балла)** Реализуйте функцию, принимающую на вход матрицу X и два массива i и j одинаковой длины и возвращающую вектор np.array, состоящий из последовательности элементов [X[i[0], j[0]], X[i[1], j[1]], ..., X[i[N-1], j[N-1]]].

In [8]:
def construct_array(X, i, j):
    # Your code here

SyntaxError: unexpected EOF while parsing (<ipython-input-8-8d879770ca20>, line 2)

**2. (0.5 балла)** Реализуйте функцию для подсчёта произведения ненулевых элементов на диагонали прямоугольной матрицы.
Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответом является 3. Если ненулевых элементов нет, функция должна возвращать *None*.

In [ ]:
def nonzero_product(X):
    # Your code here

**3. (0.5 балла)** Написать функцию, возвращающую максимальный элемент в массиве *x* среди элементов, перед которыми стоит нулевой. Для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответом является 5. Если подходящих элементов нет, функция должна возвращать *None*.

In [54]:
#help(np.dstack)
#help(np.apply_along_axis)

def max_element(arr):
    x = arr[1:]
    iy = np.where((arr[:-1] == 0))
    return np.max(x[iy])

    
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max_element(x)


5

**4. (0.5 балла)** Реализуйте функцию, принимающую на вход матрицу *X* и некоторое число *v* и возвращающую ближайший к заданному числу элемент матрицы. Например, для X = np.arange(0,10).reshape((2, 5)) и v = 3.6 ответом будет 4.

In [14]:
def nearest_value(X, v):
    X1 = np.reshape(X, (1,-1))
    a = X1 - v
    return X1[:, (a*a).argmin() ]

nearest_value(np.arange(0,10).reshape(2,5), 4.7 )

array([5])

**5. (0.5 балла)** Реализуйте функцию, принимающую на вход матрицу *X* и возвращающую все её уникальные строки в виде матрицы.

In [ ]:
def get_unique_rows(X):
    # Your code here

**6. (0.5 балла)** Реализуйте функцию, каторая во входной вещественной матрице *X* находит все значения *nan* и заменяет их на среднее арифметическое всех остальных элементов. В случае матрицы из одних *nan* произведите замену на нули.

In [89]:
def replace_nans(X):
    notnan = X[np.where(np.logical_not(np.isnan(X)))] 
    if notnan.size == 0:
        X[::] = 0
    else:
        mean = np.mean( notnan )
        X[np.where(np.isnan(X))] = mean
    
    return X

def replace_nans2(X):
    X[np.where(np.isnan(X))] = np.nanmean(X)
    return X

#print(np.mean([]))
x = np.random.random((3,4))
x[([0,1,0,2],
   [0,0,1,2])] = np.nan
print(x)
print(replace_nans(x))
 
x = np.array([np.nan, np.nan])
print(x)
print(replace_nans(x))

 
x = np.array([np.nan, np.nan])
print(x)
print(replace_nans2(x))

[[        nan         nan  0.45438436  0.0515955 ]
 [        nan  0.57708277  0.90056031  0.02545071]
 [ 0.42485823  0.21054821         nan  0.06516548]]
[[ 0.3387057   0.3387057   0.45438436  0.0515955 ]
 [ 0.3387057   0.57708277  0.90056031  0.02545071]
 [ 0.42485823  0.21054821  0.3387057   0.06516548]]
[ nan  nan]
[ 0.  0.]
[ nan  nan]
[ nan  nan]


/nix/store/njpicn24zjmad7wld6msl01g0wixr8sx-python3.5-numpy-1.11.1/lib/python3.5/site-packages/numpy/lib/nanfunctions.py:675: RuntimeWarning: Mean of empty slice
  warnings.warn("Mean of empty slice", RuntimeWarning)


**7. (0.5 балла)** Реализуйте функцию, принимающую на вход два одномерных массива *x* и *y* одинаковой длины и возвращающую матрицу, в которой первый массив соответствует первому столбцу матрицы, второй — второму. В этом задании *запрещается* пользоваться операцией транспонирования.

Задачу нужно решить двумя разными способами, за решение только одним способом максимально возможная оценка — 0.4.

In [100]:
def construct_matrix(x, y):
    R=np.zeros((x.size,2))
    #R[(np.arange(x.size, dtype=int),np.zeros(x.size, dtype=int))] = x
    #R[(np.arange(x.size, dtype=int),np.ones(x.size, dtype=int))] = y
    R[:,0] = (x,y)
    R[:,1] = y
    return R

x = np.array([0,1,2,3])
y = np.array([4,5,6,7])
construct_matrix(x,y)

ValueError: shape mismatch: value array of shape (2,4) could not be broadcast to indexing result of shape (2,4)

**8. (1.5 балла)** Даны две вещественные матрицы *X* и *Y* с одинаковым числом столбцов и, в общем случае, различным числом строк. Необходимо реализовать функцию, вычисляющую матрицу попарных евклидовых расстояний между всеми элементами декартового произведения строк *X* и *Y*. Рекомендуется обратить внимание на функции *np.dot*, *np.repeat*, *np.reshape*, *np.transpose*, *np.sqrt*, *np.sum* и *np.power*. Но не запрещается пользоваться аналогами.

In [7]:
def count_euclidean_distance(X, Y):
    # Your code here
    n,p = X.shape
    m,p = Y.shape
    print(X)
    print(Y)
    Xr = X.reshape(p,n,1)
    Yr = Y.reshape(p,1,m)
    print(Xr)
    print(Yr)

a = np.random.random((3,3))
b = np.random.random((2,3))

count_euclidean_distance(a,b)


[[ 0.24839239  0.66690662  0.3576816 ]
 [ 0.85955315  0.3929484   0.78111113]
 [ 0.27911981  0.2966596   0.67117094]]
[[ 0.78699482  0.57569034  0.44831188]
 [ 0.45827092  0.25946062  0.4962237 ]]
[[[ 0.24839239]
  [ 0.66690662]
  [ 0.3576816 ]]

 [[ 0.85955315]
  [ 0.3929484 ]
  [ 0.78111113]]

 [[ 0.27911981]
  [ 0.2966596 ]
  [ 0.67117094]]]
[[[ 0.78699482  0.57569034]]

 [[ 0.44831188  0.45827092]]

 [[ 0.25946062  0.4962237 ]]]


**9. (1 балл)** Написать функцию, которая получает на вход матрицу и масштабирует каждый её столбец, а именно вычитает из столбца его среднее значение и делит столбец на стандартное отклонение. Для тестирования можно сгенерировать с помощью метода *numpy.random.randint* случайную матрицу и проверить на ней работу метода.  Убедитесь, что в функции не будет происходить деления на ноль. 

In [ ]:
def scale(X):
    # Your code here

**10. (1 балл)** Реализуйте функцию, которая для заданной матрицы находит:
 - определитель
 - след
 - наименьший и наибольший элементы
 - норму Фробениуса
 - собственные числа
 - обратную матрицу

Для тестирования сгенерируйте матрицу с элементами из нормального распределения *N*(10,1)

In [ ]:
def get_stats(X):
    # Your code here

**11. (1 балл)** Повторите 100 раз следующий эксперимент: сгенерируйте две матрицы размера 10×10 из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль? (в данной задаче можно использовать цикл только для повторения эксперимента) 

### (5 баллов) Pandas 

![](https://metrouk2.files.wordpress.com/2015/10/panda.jpg)

Загрузите данные о пассажирах Титаника из файлов *titanic_data.csv* и *titanic_surv.csv* и ответьте на вопросы ниже. Каждый ответ поясните.

Информация о файлах: 
 - *titanic_data.csv* содержит различную информацию о пассажирах Титаника (билет, класс, возраст и т.п.)
 - *titanic_surv.csv* содержит для каждого пассажира из первого файла информацию о том, выжил ли этот пассажир (метка 1) или нет (метка 0)

**1. (1 балл)** Сделайте join двух датафреймов в один по полю индекса. Опишите данный датасет: какое расределение женщин/мужчин в нем? Сколько пассажиров ехало в каждом классе? Какой средний/минимальный/максимальный возраст пассажиров? Сколько было выживших пассажиров?

In [ ]:
import pandas as pd

**2. (1 балл)** Верно ли, что женщины выживали чаще мужчин? Какие пассажиры выживали чаще: с более дешевыми или дорогими билетами? Верно ли, что чаще выживали более молодые пассажиры?

**3. (1 балл)** Сгруппируйте записи по классам пассажиров, в каждой группе посчитайте средний возраст. Верно ли, что во всех классах эта величина примерно одинакова?

**4. (2 балла)** Найдите все признаки, для которых есть пропуски в данных. Обычно алгоритмы по умолчанию не умеют обрабатывать такие данные. Предложите способы обработки данных с пропусками (не менее двух) и укажите достоинства/недостаки каждого. Проиллюстрируйте их на примере данного датасета.

### (2 балла) Matplotlib

Обратите внимание, что у графиков должны быть подписаны оси, заголовок графика и при необходимости обязательно наличие легенды. За отсутствие названий графиков и подписей к осям могут снижаться баллы. Все картинки должны быть самодостаточны и визуально удобны для восприятия, так чтобы не нужно было смотреть ваш код или знать задание, чтобы понять что на них изображено.

![](https://imgs.xkcd.com/comics/convincing.png)

**1. (1 балл)** Используя функцию *gen_uncertain_data* для генерации выборки, отобразите на графике синим цветом функцию *y(x)*, а также ее доверительный интервал в виде закрашенной зеленым цветом области от *y[i] - error[i]* до *y[i] + error[i]*. Полезной может оказаться функция *fill_between*.

    def gen_uncertain_data():
        x = np.linspace(0, 30, 100)
        y = np.sin(x/6*np.pi) + np.random.normal(0, 0.02, size=x.shape)
        error = np.random.normal(0.1, 0.02, size=y.shape)
        return x, y, error

**2. (1 балл)** Отобразите гистограмму распределения возрастов для каждого класса пассажиров (здесь нужно использовать данные из заданий по pandas). В результате вы должны получить три гистограммы, которые необходимо отобразить рядом друг с другом используя функцию *plt.subplots*. Каждая гистограмма должна быть нормирована. Обратите внимание на параметры *figsize*, *sharey*, *sharex* функции *plt.subplots*. Также полезными могут оказаться параметры *bins*, *normed* функции *plt.hist*.